### ISSUE TITLE
Rat db

### ISSUE THREAD

**Issue by boygaggoo** [m301/rdroid#1]
I am interested in this app, can you share the db as well ?

**Comment by m301** [comment]
Hey, 
I lost database schema but yes it can be refracted from the code. I will try and update.

**Comment by boygaggoo** [comment]
i am not a web developer, i try to figure it out and its not working as i expected. if you have working example code, just update it and push the db file, this will be really helpful. otherwise this code will not helping anyone :)

**Comment by m301** [comment]
Addressed in https://github.com/m301/rdroid/issues/7#issuecomment-817516774
