### ISSUE TITLE
i cant debug 

### ISSUE THREAD

**Issue by hwhiteh** [m301/rdroid#3]
hi i cant debug apk 

Error description: Unknown member: createcontactentry2
Error occurred on line: 429
m.createContactEntry2(Name,Null,phones,mails,Note,Website,"Home",ahome,awork)
Word: createcontactentry2

help me :(

**Comment by m301** [comment]
The contact library might have been updated, hence you are facing this error, Look https://www.b4x.com/android/help/phone.html#contacts2

**Comment by m301** [comment]
Closing in favour of #7

**Comment by graysuit** [comment]
https://github.com/graysuit/rdroid/tree/main/AdditionalLibs
