### ISSUE TITLE
Debug Error 

### ISSUE THREAD

**Issue by cymilad** [m301/rdroid#5]
Error compiling program.
Error description: Unknown member: createcontactentry2
Error occurred on line: 429
m.createContactEntry2(Name,Null,phones,mails,Note,Website,"Home",ahome,awork)
Word: createcontactentry2

![Capture](https://user-images.githubusercontent.com/22496001/58452897-58cfc180-812e-11e9-8edd-375cf534d4e7.PNG)

**Comment by cymilad** [comment]
Please list all the Basic 4 Android libraries for downlaod 🙏🙏🙏

**Comment by m301** [comment]
https://www.b4x.com/android/help/phone.html#contacts2

This should help, all the libraries must have been updated. 

Even the IDE has changed a lot, I don't even have a valid license now, Will have to setup a lot of things now. :/ 

Update: 
Below two threads can be of help 
https://www.b4x.com/android/forum/threads/create-contact-problem.26041/
https://www.b4x.com/android/forum/threads/solution-create-contact.9990/#post57748

**Comment by m301** [comment]
@graysuit has successfully compiled the APK. Please refer to issue #7

**Comment by graysuit** [comment]
@cymilad 
Here are all libs I collected: https://github.com/graysuit/rdroid/tree/main/AdditionalLibs
But even you would get some errors, due to depression. 
Try to use code at: https://github.com/graysuit/rdroid/tree/main/android
But web panel NOT ready yet.
